### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by em616** [DanMcInerney/elite-proxy-finder#10]
just with -q option

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "elite-proxy-finder.py", line 247, in proxy_checker_req
    time_or_error = self.error_handler(str(e))
TypeError: __str__ returned non-string (type SysCallError)
<Greenlet at 0xb642b9dcL: <bound method find_http_proxy.proxy_checker_req of <__main__.find_http_proxy instance at 0xb644f44c>>('179.124.212.137:80')> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "elite-proxy-finder.py", line 247, in proxy_checker_req
    time_or_error = self.error_handler(str(e))
TypeError: __str__ returned non-string (type SysCallError)
<Greenlet at 0xb583066cL: <bound method find_http_proxy.proxy_checker_req of <__main__.find_http_proxy instance at 0xb644f44c>>('118.143.114.130:8080')> failed with TypeError

**Comment by DanMcInerney** [comment]
Do you still get this? I can't reproduce.

gevent 1.0.1
requests 2.7.0

**Comment by mraxlux** [comment]
I do get it on debian 8. Python 2.7.9
