### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by EwenMcMillan** [DanMcInerney/elite-proxy-finder#19]
Hi Dan
I have gevent 1.2.1, requests 2.14.2 and BeautifulSoup 3.2.1. Python is 2.7.13

Running script I get

$ python elite-proxy-finder.py -a
[*] Your accurate external IP: xxx.xxx.xxx.xxx
Traceback (most recent call last):
  File "elite-proxy-finder.py", line 400, in <module>
    P.run()
  File "elite-proxy-finder.py", line 64, in run
    gatherproxy_list = self.gatherproxy_req()
  File "elite-proxy-finder.py", line 182, in gatherproxy_req
    gatherproxy_list = self.parse_gp(lines)
  File "elite-proxy-finder.py", line 195, in parse_gp
    hex_port = l.split("'")[1]
IndexError: list index out of range

**Comment by HoussemCharf** [comment]
https://github.com/DanMcInerney/elite-proxy-finder/issues/18
